config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'relatorio_os' => 'relatorio_os#index'
post 'relatorio_os' => 'relatorio_os#show'

app/controllers/relatorio_os_controller.rb
# encoding: UTF-8

class RelatorioOsController < ApplicationController
	unloadable

	helper IssuesHelper
	helper JournalsHelper
	helper CustomFieldsHelper
	helper SortHelper
	
	def index
		find_project
	end
	
	def show
		find_project
		
		show_error("Projeto não encontrado!") and return unless @project
		
		params[:issue] ||= {}
		@issue = @project.issues.find_by_id(params[:issue][:id])
		show_error("Tarefa não encontrada!") and return unless @issue
		
		params[:history] ||= {}
		
		@start_date = params[:history][:start_date].blank? ? Date.today.to_s    : params[:history][:start_date]
		@end_date   = params[:history][:end_date].blank?   ? Date.tomorrow.to_s : params[:history][:end_date]
		
		@start_date = Date.parse(@start_date).at_midnight
		@end_date   = (Date.parse(@end_date)+1.day).at_midnight
		
		@fieldset_abertos = 0
		
		render :layout => false
	end
	
	private
	
	def find_project
		@project = Project.find(params[:project_id]) rescue nil
	end
	
	def show_error(msg)
		flash[:error] = msg 
		redirect_to(:action => 'index', :project_id => @project.id)
	end
end

app/helpers/relatorio_os_helper.rb
module RelatorioOsHelper

end

app/views/issues/_action_menu.html.erb
<div class="contextual">
<%= link_to_if_authorized(l(:button_update), {:controller => 'issues', :action => 'edit', :id => @issue }, :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit)) %>
<%= link_to l(:button_log_time), new_issue_time_entry_path(@issue), :class => 'icon icon-time-add' if User.current.allowed_to?(:log_time, @project) %>
<%= link_to('Relatório de OS', relatorio_os_path(:project_id => @project.id, :issue_id => @issue.id), :class => 'icon icon-relatorio-os') if @project.module_enabled?(:relatorio_os) %>
<%= watcher_tag(@issue, User.current) %>
<%= link_to_if_authorized l(:button_copy), {:controller => 'issues', :action => 'new', :project_id => @project, :copy_from => @issue}, :class => 'icon icon-copy' %>
<%= link_to l(:button_delete), issue_path(@issue), :data => {:confirm => issues_destroy_confirmation_message(@issue)}, :method => :delete, :class => 'icon icon-del' if User.current.allowed_to?(:delete_issues, @project) %>
</div>


<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'icon_relatorio_os', :plugin => 'questor_relatorio_os' %>
<% end %>

app/views/relatorio_os/_assinatura.html.erb
<div id="assinaturas">
	<hr />
	<div>Declaro que a solicitação descrita foi completamente atendida e o sistema encontra-se em perfeito estado de funcionamento</div>
	<div><b>Data:</b> <%= format_date(Date.today) %></div>
	
	<div class="assinatura">
		<hr />
		<div class="responsavel"><%= @issue.assigned_to %></div>
		<div class="empresa">Questor Sistemas Ltda</div>
	</div>
	
	<div class="assinatura">
		<hr />
		<div class="responsavel"> Assinatura do cliente </div>
		<br>
	</div>
</div>

app/views/relatorio_os/_estilo.html.erb
<style type="text/css" media="all">
	html,body{
		font-size: 10pt;
	}
	
	.wiki-anchor {display: none}
	
	fieldset{
		margin-top: 5px;
		border: 1px solid #999;
	}
	
	fieldset legend{
		font-weight:bold;
	}
	
	fieldset p{
		margin-top: 0px;
	}
	
	.issue{
		margin-top: 10px;
	}
	
	.issue h2{
		margin: 0px;
	}
	
	.issue .issue_header td{
		width: 1000px;
	}
	
	ul.checklist{ 
		margin: 0px; padding: 0px;
		list-style-type: none;
		
	}
	
	table td{
		font-size:11pt;
	}
	
	table.estilo{
		border-spacing:0;
		border-collapse:collapse;
	}
	
	table.estilo thead{
		font-weight: bold;
		text-align: center;
	}
	
	table.estilo .titulo{
		font-weight: bold;
		text-align: right;
	}
	
	table.estilo td{
		font-size:10pt;
		padding: 2px 10px;
		border-bottom: 1px solid #999;
	}
	
	div.journal{
		margin: 0px 15px;
	}
	
	div.journal .contextual{
		display: none;
	}
	
	div.journal ul.details{
		margin: 0px;
	}
	
	div.journal h4{
		margin-bottom: 1px;
	}
	
	div#header{
		border-spacing:0;
		border-collapse:collapse;
		border: 1px solid #999;
		margin-bottom: 20px;
		padding: 5px;
	}
	
	div#header h2{
		font-size:12pt;
		margin: 2px;
	}
	
	
	div#assinaturas{
		margin-top: 20px;
		position: relative;
		page-break-inside: avoid;
	}
	
	div.assinatura{
		display: inline-block;
		width: 40%;
		margin: 40px 4% 0px 4%;
	}
	hr{
		border: 1px solid #999;
	}
	div.assinatura .responsavel, div.assinatura .empresa{
		text-align:center;
	}
</style>

app/views/relatorio_os/_header.html.erb
<div id="header">
	<h2> Questor Sistemas Ltda</h2>
	<div style='display: inline-block;margin-right: 20px'><b>Fone/Fax:</b>(49) 3361-8100</div>
	<div style='display: inline-block;'><b>E-mail:</b>atendimento@questor.com.br</div>
	<div>Chapecó - SC</div>
	
	<hr />
	<div><b>Cliente:</b> <%= @issue.project %></div>
	<div> Relatório considerando históricos de <%= format_date(@start_date) %> a <%= format_date(@end_date-1.day) %> </div>
</div>

app/views/relatorio_os/_issue.html.erb
<% 
IssueRelation
relation_type ||= nil
children ||= nil

time_entries = issue.time_entries.where(:spent_on => (@start_date..@end_date))
journals = issue.journals.where(:private_notes => false, :created_on => (@start_date..@end_date))

if params[:issue][:only_my_records] 
	time_entries = time_entries.where(:user_id => User.current)
	journals = journals.where(:user_id => User.current)
end
%>

<% if time_entries.any? || journals.any? %>

<% @fieldset_abertos += 1  %>
<fieldset class="issue" issue="<%= issue.id %>">
	<legend><h2> <%= relation_type %> <%= issue.tracker %> #<%= issue.id %> - <%= issue.subject %></h2></legend>
	<table class='issue_header' width='100%'>
		<tr>
			<td><b>Inicio:      </b><%= format_date(issue.start_date) %></td>
			<td><b>Situação:    </b><%= issue.status %>                 </td>
			<td><b>Conclusão:   </b><%= format_date(issue.due_date) %> ( <%= issue.done_ratio %>% ) </td>
			<td><b>Responsável: </b><%= issue.assigned_to %>            </td>
		</tr>
	<% unless issue.description.blank? %>	
		<tr>
			<td colspan='4'>
				<b>Descrição:</b><%= textilizable(issue, :description) %>
			</td>
		</tr>
	<% end %>
	</table>
	
	
	<%= render(:partial => 'issue_time_entries',   :locals => { :issue => issue, :time_entries => time_entries }) if time_entries.any? %>
	<%= render(:partial => 'issue_checklist',      :locals => { :issue => issue }) if issue.respond_to?(:checklist) && issue.checklist.any? %>
	<%= render(:partial => 'issue_history',        :locals => { :issue => issue, :journals => journals }) if journals.any? %>
	<%# render(:partial => 'issue_related_issues', :locals => { :issue => issue }) unless relation_type || issue.relations.empty? %>
	
<% end %>

	<% if children && issue.children.any? %>
		<% issue.children.each do |child| %>
			<%= render(:partial => 'issue', :locals => {:issue => child, :children => true}) %>
			<%= ("</fieldset>"*@fieldset_abertos).html_safe %>
			<% @fieldset_abertos = 0 %>
		<% end %>
	<% end %>
	

<%# nao fecha o fieldset de propósito %>

app/views/relatorio_os/_issue_checklist.html.erb
<fieldset>
	<legend><h3>Checklist</h3></legend>
	<ul class='checklist'>
		<% issue.checklist.order('position').each do |cl| %>
		<li>
			<%= check_box_tag(:checklist, 1, cl.is_done) %>
			<%= cl.subject %>
		</li>
		<% end %>
	</ul>
</fieldset>

app/views/relatorio_os/_issue_history.html.erb
<fieldset>
	<legend><h3>Histórico</h3></legend>
	<% journals.each do |journal| %>
	<b>Atualizado por <%= link_to(journal.user, journal.user.name) %> em <%= format_time(journal.created_on) %>:</b>
	
  <% if journal.details.any? %>
  <ul class="details">
    <% details_to_strings(journal.details).each do |string| %>
     <li><%= string %></li>
    <% end %>
  </ul>
  <% end %>
	
	<%= textilizable(journal, :notes) unless journal.notes.blank? %>
	<% end %>
</fieldset>

app/views/relatorio_os/_issue_related_issues.html.erb
<fieldset>
	<legend><h3>Tarefas Relacionadas</h3></legend>
	<% issue.relations.each do |rel| %>
		<%= render(:partial => 'issue', :locals => {:issue => rel.other_issue(issue), :relation_type => rel.relation_type.to_s}) %>
	<% end %>
</fieldset>

app/views/relatorio_os/_issue_time_entries.html.erb
<fieldset id="tempo_gasto" class="">
	<legend><h3>Tempo Gasto</h3></legend>
	<table class='estilo'>
		<thead>
			<tr>
				<td>Data</td>
				<td>Usuário</td>
				<td>Comentário</td>
				<td>Tempo Gasto</td>
			</tr>
		</thead>
		<% time_entries.each do |entry| -%>
		<tr class="time-entry <%= cycle("odd", "even") %>">
			<td class="spent_on"><%= format_date(entry.spent_on) %></td>
			<td class="user"><%= link_to_user(entry.user) %></td>
			<td class="comments"><%=h entry.comments %></td>
			<td class="hours"><%= html_hours("%.2f" % entry.hours) %></td>
		</tr>
		<% end -%>
		<tr>
			<td colspan='3' class='titulo'>Total</td>
			<td class="hours"><%= html_hours("%.2f" % time_entries.sum(:hours)) %></td>
		</tr>
	</table>	
</fieldset>

app/views/relatorio_os/index.html.erb
<h1>Impressão de relatório de OS</h1>

<fieldset>
	<legend>Filtros</legend>
	<%= form_for(:issue, :url => {:controller => 'relatorio_os', :action => 'show', :project_id => @project.id}) do |f| %>
	
		Imprimir o relatório da tarefa <%= f.text_field(:id, :size => 3, :value => (params[:issue_id] || '')) %>
		<br>
		Filtrar histórico entre os dias: 
			<%= text_field_tag :history_start_date, format_date(Date.today), :name => 'history[start_date]', :size => 10 %><%= calendar_for('history_start_date') %>
		e: 
			<%= text_field_tag :history_end_date, format_date(Date.today), :name => 'history[end_date]', :size => 10 %><%= calendar_for('history_end_date') %>
		<br>
		<%= f.label(:only_my_records, "Trazer somente meus registros?") %>
		<%= f.check_box(:only_my_records, {:checked => true}, true, false) %>
		<br>
		<%= f.submit('Imprimir') %>
		
	<% end %>
</fieldset>


<script type="text/javascript" charset="utf-8">
	$('#issues_start_id').focus();
</script>

app/views/relatorio_os/show.html.erb
<html>
	<head>
		<title>Relatório de OS - <%= @issue.tracker %> #<%= @issue.id %> - <%= @issue.subject %></title>
		<%= render('estilo') %>
	</head>
	<body>
			<%= render('header') %>
			<div class="issues">
				
				<%= render(:partial => 'issue', :collection => @issue.ancestors, :as => :issue) %>
				
				<%= render(:partial => 'issue', :locals => {:issue => @issue, :children => true}) %>
				
				<%= ("</fieldset>"*@fieldset_abertos).html_safe %>
				<% @fieldset_abertos = 0 %>
			</div>
			
			<%= render('assinatura') %>
	</body>
</html>